services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amp_backend
    environment:
      - NODE_ENV=production
      - ELASTICSEARCH_URL=http://127.0.0.1:9200
      - REDIS_URL=redis://127.0.0.1:6379
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./uploads
        target: /app/uploads
    restart: unless-stopped
    network_mode: "host"